In [4]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


In [5]:
#Task 01 : Use numpy to create a 3×3 matrix of random integers between 1 and 50.
Matrix = np.random.randint(1, 50, (3, 3))
print(Matrix)


[[10 26  8]
 [46  3  2]
 [38  2 45]]


In [6]:
#Task 2 : Use numpy to create a 3×3 matrix of random integers between 1 and 50. With a fixed seed (`np.random.seed(10)`) to ensure reproducibility.
np.random.seed(10)
Matrix = np.random.randint(1, 50, (3, 3))
print(Matrix)

[[10 37 16]
 [ 1 29 26]
 [30 49 30]]


# Explanation:



### Task 1: Random Matrix Without a Fixed Seed
When you generate a 3×3 matrix of random numbers without setting a seed, the values change every time you run the code. This happens because the random number generator is initialized differently each time, producing new random values. This is useful when you need fresh randomness for things like simulations or testing.

### Task 2: Random Matrix With a Fixed Seed (np.random.seed(10))
By setting a fixed seed (like np.random.seed(10)), you ensure the same random numbers are generated every time you run the code. This makes the results predictable and repeatable. It’s important for consistency in tests, debugging, or research where you need the same outcomes.

### Why Use a Seed?
**Reproducibility**: Helps you get the same results every time, making tests reliable.
**Consistency**: Ensures everyone gets the same results if they run the same code.
**Controlled Randomness**: Useful when you need repeatable results in simulations, machine learning, or research.